<?php

/**
 * @file
 * Contains headshots.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function headshots_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the headshots module.
    case 'help.page.headshots':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Headshots Module') . '</p>';
      return $output;

    default:
  }
}
